{{ if and .Values.repository.createSecret (not .Values.repository.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "restic-pvc-backup.secretName" . }}
  labels:
    {{ include "restic-pvc-backup.labels" . | nindent 4 }}
type: Opaque
stringData:
{{ range $key, $value := .Values.repository.stringData }}
  {{ $key }}: {{ $value | quote }}
{{ end }}
{{ end }}
